import type { AdminData } from './types'

export const initialAdminData: AdminData = {
  partners: [
    {
      id: 'P-1001',
      registeredAt: '2026-02-20',
      name: 'Иван Петров',
      contact: '+7 901 123-45-67 / ivan@test.ru',
      level: 'base',
      status: 'active',
      adminComment: 'Стартовый партнер, аккуратная передача лидов.',
      features: {
        advancedReporting: false,
        bulkLeadUpload: false,
        apiIntegration: false,
        multiReferralLinks: false,
        customRewardModel: false,
      },
      extraFields: {
        companyName: false,
        trafficSource: false,
        telegram: false,
        contractNumber: false,
      },
      rewardModelId: 'R-1',
      rewardOverride: null,
    },
    {
      id: 'P-1002',
      registeredAt: '2026-02-15',
      name: 'Мария Смирнова',
      contact: '+7 903 987-00-11 / maria@test.ru',
      level: 'extended',
      status: 'active',
      adminComment: 'Дать доступ к нескольким ссылкам и отчетности.',
      features: {
        advancedReporting: true,
        bulkLeadUpload: false,
        apiIntegration: false,
        multiReferralLinks: true,
        customRewardModel: false,
      },
      extraFields: {
        companyName: true,
        trafficSource: true,
        telegram: true,
        contractNumber: false,
      },
      rewardModelId: 'R-2',
      rewardOverride: null,
    },
    {
      id: 'P-1003',
      registeredAt: '2026-02-11',
      name: 'Алексей Орлов',
      contact: '+7 905 777-88-99 / alex@test.ru',
      level: 'max',
      status: 'blocked',
      adminComment: 'Временно заблокирован до уточнения качества лидов.',
      features: {
        advancedReporting: true,
        bulkLeadUpload: true,
        apiIntegration: true,
        multiReferralLinks: true,
        customRewardModel: true,
      },
      extraFields: {
        companyName: true,
        trafficSource: true,
        telegram: true,
        contractNumber: true,
      },
      rewardModelId: 'R-3',
      rewardOverride: 6200,
    },
  ],
  leads: [
    {
      id: 'L-9001',
      partnerId: 'P-1001',
      createdAt: '2026-03-01',
      clientName: 'Сергей Иванов',
      phone: '+7 999 000-11-22',
      status: 'new',
      comment: 'Просил перезвонить вечером',
      history: [{ status: 'new', at: '2026-03-01 10:10', note: 'Лид создан' }],
    },
    {
      id: 'L-9002',
      partnerId: 'P-1002',
      createdAt: '2026-02-28',
      clientName: 'Екатерина Новикова',
      phone: '+7 999 100-22-33',
      status: 'in_progress',
      comment: 'Уточнить регион регистрации',
      history: [
        { status: 'new', at: '2026-02-28 09:00', note: 'Лид создан' },
        { status: 'in_progress', at: '2026-02-28 11:40', note: 'Взят в работу оператором' },
      ],
    },
    {
      id: 'L-9003',
      partnerId: 'P-1003',
      createdAt: '2026-02-27',
      clientName: 'Олег Ким',
      phone: '+7 999 200-33-44',
      status: 'accepted',
      comment: 'Полный пакет данных',
      history: [
        { status: 'new', at: '2026-02-27 12:00', note: 'Лид создан' },
        { status: 'in_progress', at: '2026-02-27 12:30', note: 'Взят в работу' },
        { status: 'accepted', at: '2026-02-27 14:15', note: 'Лид принят' },
      ],
    },
  ],
  rewardModels: [
    {
      id: 'R-1',
      name: 'Базовая модель',
      amountPerLead: 3500,
      comment: 'Стартовый тариф для новых партнеров',
    },
    {
      id: 'R-2',
      name: 'Расширенная модель',
      amountPerLead: 4500,
      comment: 'Для стабильных партнеров с хорошим качеством',
    },
    {
      id: 'R-3',
      name: 'Максимальная модель',
      amountPerLead: 6000,
      comment: 'Индивидуальные условия и приоритет',
    },
  ],
  operators: [
    { id: 'U-1', name: 'Анна Оператор', email: 'operator@test.ru', role: 'operator', status: 'active' },
    { id: 'U-2', name: 'Старший Оператор', email: 'lead-op@test.ru', role: 'operator', status: 'blocked' },
  ],
  settings: {
    supportLink: 'https://t.me/example_support',
    platformName: 'NSSD CPA',
    platformNote: 'Управление партнерами и доступами',
  },
}
